In [2]:
import pandas as pd
import re
import numpy as np

In [3]:
# Load the dataset from the CSV file
df = pd.read_csv('../Datasets/resortworldwide.csv')

In [4]:
# Display the first 5 rows of the DataFrame
df.head()

,URL,Rate,NameResort,Stars,Km Freeride,Continent,Country,State/Province,Altitude,Easy,...,Après-ski,Accommodation offering directly at the slopes and lifts,Families and children,Beginners,Snow parks,Cross-country skiing and trails,country,latitude,longitude,Total Kms
0,http://www.skiresort.info/ski-resort/kitzski-k...,4.9,KitzSki – Kitzbühel/Kirchberg,5.0,45.0,Europe,Austria,Tyrol (Tirol),2000.0,101.0,...,"4,0","5,0","5,0","5,0","5,0","5,0",AT,47.516231,14.550072,179
1,http://www.skiresort.info/ski-resort/ischglsam...,4.8,Ischgl/Samnaun – Silvretta Arena,5.0,15.0,Europe,Austria,Tyrol (Tirol),2872.0,47.0,...,"5,0","5,0","4,0","4,0","5,0","4,0",AT,47.516231,14.550072,238
2,http://www.skiresort.info/ski-resort/skiwelt-w...,4.8,SkiWelt Wilder Kaiser-Brixental,5.0,26.0,Europe,Austria,Tyrol (Tirol),1957.0,122.0,...,"4,0","4,0","5,0","5,0","5,0","5,0",AT,47.516231,14.550072,284
3,http://www.skiresort.info/ski-resort/st-antons...,4.8,Ski Arlberg,5.0,200.0,Europe,Austria,Tyrol (Tirol),2811.0,132.0,...,"5,0","5,0","5,0","5,0","4,0","4,0",AT,47.516231,14.550072,305
4,http://www.skiresort.info/ski-resort/serfaus-f...,4.8,Serfaus-Fiss-Ladis,5.0,28.0,Europe,Austria,Tyrol (Tirol),2820.0,47.0,...,"4,0","4,0","5,0","4,0","5,0","4,0",AT,47.516231,14.550072,198

In [5]:
import pandas as pd

def generate_alphanumeric_id(prefix, idx):
    """
    Generates an alphanumeric ID with a given prefix and index.
    
    Parameters:
    - prefix (str): The prefix for the ID.
    - idx (int): The numeric index for the ID.
    
    Returns:
    - str: An alphanumeric ID.
    """
    return f"{prefix}{idx+1:03d}"  # Adding 1 to idx to start from 1 instead of 0

# Assuming you have a DataFrame named df containing ski resort information

# Generate unique IDs for each resort based on the URL
resort_urls = df['URL']

# Generate Alphanumeric IDs
alphanumeric_ids = [generate_alphanumeric_id("RES", i) for i in range(len(resort_urls))]

# Create a mapping DataFrame
resort_ids_df = pd.DataFrame({
    'Resort ID': alphanumeric_ids,
    'URL': resort_urls,
    'Resort Name': df['NameResort']  # Assuming 'NameResort' is the column containing resort names
})

# Display the Resort IDs table
resort_ids_df

,Resort ID,URL,Resort Name
0,RES001,http://www.skiresort.info/ski-resort/kitzski-k...,KitzSki – Kitzbühel/Kirchberg
1,RES002,http://www.skiresort.info/ski-resort/ischglsam...,Ischgl/Samnaun – Silvretta Arena
2,RES003,http://www.skiresort.info/ski-resort/skiwelt-w...,SkiWelt Wilder Kaiser-Brixental
3,RES004,http://www.skiresort.info/ski-resort/st-antons...,Ski Arlberg
4,RES005,http://www.skiresort.info/ski-resort/serfaus-f...,Serfaus-Fiss-Ladis
...,...,...,...
5473,RES5474,http://www.skiresort.info/ski-resort/snowland-...,snowland-gramado
5474,RES5475,http://www.skiresort.info/ski-resort/ski-namibia/,ski-namibia
5475,RES5476,http://www.skiresort.info/ski-resort/sky-resor...,sky-resort-ulaanbaatar
5476,RES5477,http://www.skiresort.info/ski-resort/snow-city...,snow-city-singapore
5477,RES5478,http://www.skiresort.info/ski-resort/troodos-m...,troodos-mount-olympos

In [6]:
# Export your DataFrame to CSV
resort_ids_df.to_csv('../Resources/Processed/resorts_name.csv', index=False)

OSError: Cannot save file into a non-existent directory: '..\Resources\Processed'

In [ ]:
# Drop columns where all values are 0
df = df.loc[:, (df != 0).any(axis=0)]

df.info()

In [ ]:
# Create the 'Resort ID' column with values ranging from 1 to the length of the DataFrame
df['Resort ID'] = range(1, len(df) + 1)

# Reorder the columns to make 'Resort ID' the first column
df = df[['Resort ID'] + [col for col in df.columns if col != 'Resort ID']]

# Display the DataFrame with 'Resort ID' as the first column
df.tail()

In [ ]:
# Selecting the required columns
location_df = df[['Resort ID', 'NameResort', 'Continent', 'Country', 'State/Province']]

# Renaming columns for consistency
location_df.columns = ['Resort ID', 'Resort Name', 'Continent', 'Country', 'State/Province']

# Displaying the Location table DataFrame
location_df

In [ ]:
# Remove rows with NaN values in any column
europe_location_df = europe_location_df.dropna()

# Display the updated ratings table DataFrame
europe_location_df

In [ ]:
places = location_df["State/Province"].unique().tolist()

# Print the list of unique states/provinces
print(places)

In [ ]:
# Export your DataFrame to CSV
europe_location_df.to_csv('../Resources/Processed/location.csv', index=False)

In [ ]:
# Remove extra whitespace from column names
df.columns = df.columns.str.strip()

# Create Difficulty Table
difficulty_df = df[['Resort ID', 'Easy', 'Intermediate', 'Difficult']].copy()

# Display the first few rows of the Difficulty Table
difficulty_df

In [ ]:
# Remove rows with NaN values in any column
difficulty_df = difficulty_df.dropna()

# Display the updated ratings table DataFrame
difficulty_df

In [ ]:
# Export your DataFrame to CSV
difficulty_df.to_csv('../Resources/Processed/difficulty.csv', index=False)

In [ ]:
# Select 'Adult' and 'Currency' columns
price_df = df[['Resort ID', 'Adult', 'Currency']].copy()

# Remove rows with null values in either 'Adult' or 'Currency' column
price_df = price_df.dropna(subset=['Adult', 'Currency'])

# Display the first few rows of the Price Table
price_df.head()

In [ ]:
# Convert 'Adult' column to numeric data type
price_df['Adult'] = pd.to_numeric(price_df['Adult'], errors='coerce')

# Iterate through the DataFrame and convert prices to GBP for European currencies
for index, row in price_df.iterrows():
    currency = row['Currency']
    if currency in exchange_rates:
        # Convert the price to GBP using the exchange rate
        price_df.at[index, 'Adult'] *= exchange_rates[currency]

# Display the updated DataFrame
print(price_df)

In [ ]:
# Define exchange rates relative to GBP for European currencies
exchange_rates = {
    'European Euro': 1.0,  
    'Swiss Franc': 1.2,     
    'Bulgarian Lev': 0.5,   
    'Serbian dinar': 0.01,  
    'Norwegian krone': 0.11, 
    'Swedish krona': 0.12,   
    'Danish Krone': 0.13,    
    'Polish zloty': 0.21,    
    # Add other European currencies and their exchange rates
}



# Iterate through the DataFrame and convert prices to GBP for European currencies
for index, row in price_df.iterrows():
    currency = row['Currency']
    if currency in exchange_rates:
        # Convert the price to GBP using the exchange rate
        price_df.at[index, 'Adult'] *= exchange_rates[currency]
        # Update the currency to GBP
        price_df.at[index, 'Currency'] = 'GBP'

# Display the updated DataFrame
price_df.head(50)

In [ ]:
# Remove rows with NaN values in the 'Adult' column
price_df = price_df.dropna(subset=['Adult'])

# Display the updated DataFrame without NaN values in the 'Adult' column
price_df

In [ ]:
# Export your DataFrame to CSV
price_df.to_csv('../Resources/Processed/price.csv', index=False)

In [ ]:
# Selecting the required columns for the ratings table
ratings_df = df[['Resort ID', 'Rate', 'Stars']].copy()

# Displaying the ratings table DataFrame
ratings_df

In [ ]:
# Remove rows with NaN values in any column
ratings_df = ratings_df.dropna()

# Display the updated ratings table DataFrame
ratings_df

In [ ]:
# Export your DataFrame to CSV
ratings_df.to_csv('../Resources/Processed/ratings.csv', index=False)